name: publish-web

on:
  push:
    branches:
      - main

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: expo/expo-github-action@v5

      - run: yarn install

      - name: Build
        run: expo build:web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
          commit_message: ${{ github.event.head_commit.message }}